# -------------------------------------------------------------------
# Kitty as default
$terminal = uwsm app -- kitty

# -------------------------------------------------------------------
# LOOK AND FEEL
# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    gaps_in = 4
    gaps_out = 4

    # Use master layout instead of dwindle
    layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

animations {
    enabled = false
}

# -------------------------------------------------------------------
# KEYBINGS
# Window focus with hjkl (vim-style)
unbind = SUPER, K
unbind = SUPER, J
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

unbind = SUPER, F
bind = SUPER, F, fullscreen, 1

# Swap SUPER and ALT keys
input {
    kb_options = altwin:swap_alt_win
}

# Monitor mirroring
# monitor=eDP-1,preferred,0x0,1
# monitor=DP-7,preferred,0x0,1
